# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f57f2fc5ba5bf8c2699f9aa6ac89ab2ff5675f3af09b65738a72720a19c68de01fef1bcc0bf29bdcede6a36d59d1f711507ef3cb955d7dad4773ae353e2b0315

test:
  secret_key_base: 53889faa9331250b05ce1699e85be425d201c620d37306065cc7aa9d105cf0219a54453f62ba149efea7fcd083ca541f35cc2cc42e674137961498c0470f7d8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
